{% set name = "epigen" %}
{% set version = "1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/msantorsola/epigen/archive/e1c4a4ee97b7dda5beb12be2eaeb5069a479b43f.zip
  sha256: 55ae22238066c270bfee220245abd633f0985c694418dccec966a56fcfae595d 
  #patches: patches

build:
  number: 0
  noarch: generic

  run_exports:
    - {{ pin_subpackage("epigen", max_pin="x") }}

requirements:
  run:
    - python >=3.3
    - matplotlib-base
    - scipy >=1.3.1
    - numpy >=1.17.3
  host:
    - python >=3.3
    - pip



test:
  commands:
    - simulate_data.py --help | grep "usage"
#    - simulate_data.py --help 2>&1 | grep "usage"

about:
  summary: "Package for EpiGEN which simulates genotype and phenotype data"
  license: "GPL-3.0-only"
  home: "https://github.com/biomedbigdata/epigen"

extra:
  identifiers:
    - doi:10.1093/bioinformatics/btaa245
  recipe-maintainers:
    - msantorsola




