{% set name = "epigen" %}
{% set version = "1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/msantorsola/epigen/archive/3656639a9d05ccb431e99ef6de57b7d0c893df64.zip
  sha256: 84b9d415802d637ff117297576a94b2738485a5f4d616ff8fa2bba4fabd2a615 
  #patches: patches

build:
  number: 0
  noarch: generic

  run_exports:
    - {{ pin_subpackage("epigen", max_pin="x") }}

requirements:
  run:
    - python >=3.3
    - matplotlib-base
    - scipy >=1.3.1
    - numpy >=1.17.3
  host:
    - python >=3.3
    - pip



test:
  commands:
    - simulate_data.py --help | grep "usage"
#    - simulate_data.py --help 2>&1 | grep "usage"

about:
  summary: "Package for EpiGEN which simulates genotype and phenotype data"
  license: "GPL-3.0-only"
  home: "https://github.com/biomedbigdata/epigen"

extra:
  identifiers:
    - doi:10.1093/bioinformatics/btaa245
  recipe-maintainers:
    - msantorsola




