{% set name = "multiqc" %}
{% set version = "1.15" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: ce5359a12226cf4ce372c6fdad142cfe2ae7501ffa97ac7aab544ced4db5ea3c

build:
  number: 1
  entry_points:
    - multiqc=multiqc.__main__:run_multiqc
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - click
    - coloredlogs
    - future >0.14.0
    - jinja2 >=3.0.0
    - lzstring
    - markdown
    - matplotlib >=2.1.1
    - networkx >=2.5.1
    - numpy
    - pip
    - python
    - pyyaml >=4
    - requests
    - rich >=10
    - rich-click
    - setuptools
    - simplejson
    - spectra >=0.0.10
  run:
    - click
    - coloredlogs
    - future >0.14.0
    - jinja2 >=3.0.0
    - lzstring
    - markdown
    - matplotlib >=2.1.1
    - networkx >=2.5.1
    - numpy
    - python
    - pyyaml >=4
    - requests
    - rich >=10
    - rich-click
    - setuptools
    - simplejson
    - spectra >=0.0.10

test:
  imports:
    - multiqc
    - multiqc.modules
    - multiqc.modules.adapterRemoval
    - multiqc.modules.afterqc
    - multiqc.modules.anglerfish
    - multiqc.modules.bamtools
    - multiqc.modules.bbduk
    - multiqc.modules.bbmap
    - multiqc.modules.bcftools
    - multiqc.modules.bcl2fastq
    - multiqc.modules.bclconvert
    - multiqc.modules.biobambam2
    - multiqc.modules.biobloomtools
    - multiqc.modules.biscuit
    - multiqc.modules.bismark
    - multiqc.modules.bowtie1
    - multiqc.modules.bowtie2
    - multiqc.modules.busco
    - multiqc.modules.bustools
    - multiqc.modules.ccs
    - multiqc.modules.cellranger
    - multiqc.modules.checkqc
    - multiqc.modules.clipandmerge
    - multiqc.modules.clusterflow
    - multiqc.modules.conpair
    - multiqc.modules.custom_content
    - multiqc.modules.cutadapt
    - multiqc.modules.damageprofiler
    - multiqc.modules.dedup
    - multiqc.modules.deeptools
    - multiqc.modules.diamond
    - multiqc.modules.disambiguate
    - multiqc.modules.dragen
    - multiqc.modules.dragen_fastqc
    - multiqc.modules.eigenstratdatabasetools
    - multiqc.modules.fastp
    - multiqc.modules.fastq_screen
    - multiqc.modules.fastqc
    - multiqc.modules.featureCounts
    - multiqc.modules.fgbio
    - multiqc.modules.filtlong
    - multiqc.modules.flash
    - multiqc.modules.flexbar
    - multiqc.modules.gatk
    - multiqc.modules.gffcompare
    - multiqc.modules.goleft_indexcov
    - multiqc.modules.gopeaks
    - multiqc.modules.happy
    - multiqc.modules.hicexplorer
    - multiqc.modules.hicpro
    - multiqc.modules.hicup
    - multiqc.modules.hifiasm
    - multiqc.modules.hisat2
    - multiqc.modules.homer
    - multiqc.modules.hops
    - multiqc.modules.htseq
    - multiqc.modules.humid
    - multiqc.modules.interop
    - multiqc.modules.ivar
    - multiqc.modules.jcvi
    - multiqc.modules.jellyfish
    - multiqc.modules.kaiju
    - multiqc.modules.kallisto
    - multiqc.modules.kat
    - multiqc.modules.kraken
    - multiqc.modules.leehom
    - multiqc.modules.librarian
    - multiqc.modules.lima
    - multiqc.modules.longranger
    - multiqc.modules.macs2
    - multiqc.modules.malt
    - multiqc.modules.methylQA
    - multiqc.modules.minionqc
    - multiqc.modules.mirtop
    - multiqc.modules.mirtrace
    - multiqc.modules.mosdepth
    - multiqc.modules.motus
    - multiqc.modules.mtnucratio
    - multiqc.modules.multivcfanalyzer
    - multiqc.modules.nanostat
    - multiqc.modules.nextclade
    - multiqc.modules.ngsderive
    - multiqc.modules.odgi
    - multiqc.modules.optitype
    - multiqc.modules.pangolin
    - multiqc.modules.pbmarkdup
    - multiqc.modules.peddy
    - multiqc.modules.phantompeakqualtools
    - multiqc.modules.picard
    - multiqc.modules.porechop
    - multiqc.modules.preseq
    - multiqc.modules.prinseqplusplus
    - multiqc.modules.prokka
    - multiqc.modules.purple
    - multiqc.modules.pychopper
    - multiqc.modules.pycoqc
    - multiqc.modules.qc3C
    - multiqc.modules.qorts
    - multiqc.modules.qualimap
    - multiqc.modules.quast
    - multiqc.modules.rna_seqc
    - multiqc.modules.rockhopper
    - multiqc.modules.rsem
    - multiqc.modules.rseqc
    - multiqc.modules.salmon
    - multiqc.modules.sambamba
    - multiqc.modules.samblaster
    - multiqc.modules.samtools
    - multiqc.modules.sargasso
    - multiqc.modules.sentieon
    - multiqc.modules.seqyclean
    - multiqc.modules.sexdeterrmine
    - multiqc.modules.sickle
    - multiqc.modules.skewer
    - multiqc.modules.slamdunk
    - multiqc.modules.snippy
    - multiqc.modules.snpeff
    - multiqc.modules.snpsplit
    - multiqc.modules.somalier
    - multiqc.modules.sortmerna
    - multiqc.modules.stacks
    - multiqc.modules.star
    - multiqc.modules.supernova
    - multiqc.modules.theta2
    - multiqc.modules.tophat
    - multiqc.modules.trimmomatic
    - multiqc.modules.umitools
    - multiqc.modules.varscan2
    - multiqc.modules.vcftools
    - multiqc.modules.vep
    - multiqc.modules.verifybamid
    - multiqc.modules.whatshap
    - multiqc.plots
    - multiqc.templates
    - multiqc.templates.default
    - multiqc.templates.default_dev
    - multiqc.templates.gathered
    - multiqc.templates.geo
    - multiqc.templates.sections
    - multiqc.templates.simple
    - multiqc.utils
  commands:
    - multiqc --help

about:
  home: "http://multiqc.info"
  license: "GNU General Public v3 (GPLv3)"
  license_family: GPL3
  license_file: 
  summary: "Create aggregate bioinformatics analysis reports across many samples and tools"
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
